### PR TITLE
Cat Dog Classifier example

### PR DESCRIPTION
**Pull request by Nelias**
This is what can be done currently for this kind of problem with brain.js version 2.0.0-beta.4. In the future another example might be created or this one updated, which would use a convolutional neural network instead of feedforward neural network.

More details are described in the cat-dog-classifier.md file.

### CODE REVIEW

**Comment by Nelias** [comment]
@robertleeplummerjr is that repository still alive? I think it would be a nice place to put some bigger Brain.js projects here, that is why I did not push my whole small "site" to the main library. I can still put some parts of it into official package.
@mubaidr what do you think?

**Comment by robertleeplummerjr** [comment]
It is, just slow going.  Does this run directly from load up?

**Comment by robertleeplummerjr** [comment]
On second thought, to prevent a monolith architecture just for examples, why don't you go ahead and put up a fully working version of this, and we'll link it here, which will be linked by brain.js.  Does that sound good and easy?

**Comment by Nelias** [comment]
Closing because: https://github.com/BrainJS/brain.js/pull/795

**Comment by Nelias** [comment]
Reopening: https://github.com/BrainJS/brain.js/pull/795#issuecomment-1505317013

**Comment by Nelias** [comment]
@robertleeplummerjr the last update in this repository was 6 months ago so maybe a new merge would give it some life :)

**Comment by robertleeplummerjr** [comment]
Thank you for your fine addition.

**Pull request merged**
